# Generated by Django 5.0.1 on 2024-05-22 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mnnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=None)),
                ('sections', models.CharField(default='', max_length=100)),
                ('embedPath', models.CharField(default='', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('username', models.CharField(default='', max_length=100)),
                ('subjects', models.CharField(default='', max_length=1000)),
                ('attendance_days', models.IntegerField(default=None)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Netra.mnnit')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('section', models.CharField(default='', max_length=10)),
                ('attendance', models.IntegerField(default=None)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Netra.mnnit')),
            ],
        ),
    ]
