# Generated by Django 5.0.1 on 2024-05-23 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Netra', '0002_rename_sections_mnnit_section_delete_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(default='', max_length=100, unique=True)),
                ('subjects', models.CharField(default='', max_length=1000)),
                ('attendance_days', models.IntegerField(default=None)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Netra.mnnit')),
            ],
        ),
    ]
