# Generated by Django 5.0.1 on 2024-05-23 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Netra', '0003_professor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
