# Generated by Django 5.0.1 on 2024-05-26 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Netra', '0004_delete_professor'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('subjects', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='detail',
        ),
        migrations.DeleteModel(
            name='Mnnit',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
