# Generated by Django 5.0.1 on 2024-05-27 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Netra', '0005_professor_remove_student_detail_delete_mnnit_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('section', models.CharField(default='', max_length=100)),
                ('year', models.CharField(default='', max_length=100)),
                ('role', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='professor',
            name='role',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
